AVRO-3232: add matches to deserialize_any union+string/map (#1368)
the deserialize_any method is used when using from_value::<T>
to deserialize a record which has fields that are not present
in <T>

the deserialize_any was missing some matches on certain
Value variants which caused errors like:

Error: DeserializeValue("Unsupported union")
Error: DeserializeValue("incorrect value of type: String")

this patch adds the missing matches and enhances the error
message to help in understanding which type could be missing in
the future

the test case added showcases the problem while validating that
union deserialization is actually working as well

Signed-off-by: Ultrabug <ultrabug@ultrabug.net>