AVRO-4032: [Rust] Make it possible to set custom compression level for all codec that support it (#3095)
* AVRO-4032: add zstd variant that allows for level config

* add docs

* manual impl for IntoStaticStr to handle 2 variants with same value

* AVRO-4032: [Rust] Add codec settings for Bzip2

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* AVRO-4032: [Rust] Add settings for Xz codec

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* add zstd settings

* make our new settings structs visible

* AVRO-4032: [Rust] Add support for Zstandard dictionary

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* AVRO-4032: [Rust] Store the codec compression_level in the header metadata

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* AVRO-4032: [Rust] Minor cleanups

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* AVRO-4032: Fix the build

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* AVRO-4032: Add tests for Codec::Null and ::Deflate

This way there is no need to enable other codecs when running unrelated tests.
Otherwise the build fails with:
```
error: function `avro_4032_codec_settings` is never used
  --> avro/tests/codecs.rs:50:4
   |
50 | fn avro_4032_codec_settings(codec: Codec) -> TestResult {
   |    ^^^^^^^^^^^^^^^^^^^^^^^^
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

---------

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>
Co-authored-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>